/*
The use of computers in education can be referred as Computer-Assisted
Instruction (CAI). Develop a program that helps elementary school students learning
multiplication. Use the ‘ rand()’ function to generate two positive one-digit integers.
The program gives the students with a question, such as
				What is the value of 6 times 7?
The student then inputs the answer. Next, the program checks the student answer.
If the answer is correct, the program displays the message “Correct” and asks
another multiplication question. If the answer is wrong, the program displays the
message “Incorrect. Please try again.” and let the student try the same
question repeatedly until the student finally answers correctly.
*/
//import the required libraries
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

int main ()
{
	int cx, cy, cz; // computer numbers
	int uz; // user number
	char gameStat = 'y'; // Game stat
	int counter = 0;// counter
	while(gameStat == 'y')
	{
		srand(time(NULL));//set the seed
		cx = 1 + (rand() % 10); //generate a number between 1 and 10
		cy = 1 + (rand() % 10); //generate a number between 1 and 10
		printf("what is the value of %d times %d ?\n", cx, cy);// aske the question 
		scanf("%d", &uz); //User's answer
		cz = cx * cy; //times the numbers with out showing to user
		//Because the nembers generated by the computer are between 1 and 10 the answer must be greater equal to 1.
		if (uz >= 1)
		{
			while(cz != uz)
			{
				printf("Incorrect. Please try again!\n");
				scanf("%d", &uz); //read User's answer again!
				counter++; //incriment the counter
			}
			if (cz == uz)
			{
				printf("correct\n");
				counter++;//incriment the counter
			}
			printf("You guessed the number after %d attempts.\n", counter);//display number of times took the user to guess the number
			printf("Would you like to play again (y or n)?\n");// asks if the user wants to play another game
			scanf(" %c", &gameStat);//reads the user input (y or n)
			if (gameStat == 'y'); //if y loop again
			else break; //otherwise exit
		} 
	}
	return 0;
}